football_data = [
    {
        "name": "Lionel Messi",
        "contract_price": 200000000,
        "age": 34,
        "efficiency": 5823529.41,
        "role": "Striker",
    },
    {
        "name": "Cristiano Ronaldo",
        "contract_price": 175000000,
        "age": 36,
        "efficiency": 4861111.11,
        "role": "Striker",
    },
    {
        "name": "Neymar Jr.",
        "contract_price": 150000000,
        "age": 29,
        "efficiency": 5172413.79,
        "role": "Forward",
    },
    {
        "name": "Kylian Mbappé",
        "contract_price": 160000000,
        "age": 23,
        "efficiency": 6956521.74,
        "role": "Forward",
    },
    {
        "name": "Robert Lewandowski",
        "contract_price": 120000000,
        "age": 32,
        "efficiency": 3750000.00,
        "role": "Striker",
    },
    {
        "name": "Sergio Ramos",
        "contract_price": 80000000,
        "age": 35,
        "efficiency": 4571428.57,
        "role": "Defender",
    },
    {
        "name": "Kevin De Bruyne",
        "contract_price": 130000000,
        "age": 30,
        "efficiency": 4333333.33,
        "role": "Midfielder",
    },
    {
        "name": "Virgil van Dijk",
        "contract_price": 100000000,
        "age": 30,
        "efficiency": 3333333.33,
        "role": "Defender",
    },
    {
        "name": "Mohamed Salah",
        "contract_price": 140000000,
        "age": 29,
        "efficiency": 4827586.21,
        "role": "Forward",
    },
    {
        "name": "Karim Benzema",
        "contract_price": 110000000,
        "age": 33,
        "efficiency": 3333333.33,
        "role": "Striker",
    },
    {
        "name": "Luka Modrić",
        "contract_price": 90000000,
        "age": 35,
        "efficiency": 2571428.57,
        "role": "Midfielder",
    },
    {
        "name": "Joshua Kimmich",
        "contract_price": 95000000,
        "age": 27,
        "efficiency": 3518518.52,
        "role": "Midfielder",
    },
    {
        "name": "Harry Kane",
        "contract_price": 120000000,
        "age": 28,
        "efficiency": 4285714.29,
        "role": "Striker",
    },
    {
        "name": "Erling Haaland",
        "contract_price": 140000000,
        "age": 21,
        "efficiency": 6666666.67,
        "role": "Striker",
    },
    {
        "name": "Sadio Mané",
        "contract_price": 90000000,
        "age": 29,
        "efficiency": 3103448.28,
        "role": "Forward",
    },
    {
        "name": "Bruno Fernandes",
        "contract_price": 120000000,
        "age": 27,
        "efficiency": 4444444.44,
        "role": "Midfielder",
    },
    {
        "name": "Manuel Neuer",
        "contract_price": 100000000,
        "age": 35,
        "efficiency": 2857142.86,
        "role": "Goalkeeper",
    },
    {
        "name": "Jadon Sancho",
        "contract_price": 85000000,
        "age": 21,
        "efficiency": 4047619.05,
        "role": "Forward",
    },
    {
        "name": "Antoine Griezmann",
        "contract_price": 120000000,
        "age": 30,
        "efficiency": 4000000.00,
        "role": "Forward",
    },
    {
        "name": "Eden Hazard",
        "contract_price": 110000000,
        "age": 30,
        "efficiency": 3666666.67,
        "role": "Forward",
    },
    {
        "name": "Raheem Sterling",
        "contract_price": 110000000,
        "age": 27,
        "efficiency": 4074074.07,
        "role": "Forward",
    },
    {
        "name": "Toni Kroos",
        "contract_price": 90000000,
        "age": 31,
        "efficiency": 2903225.81,
        "role": "Midfielder",
    },
    {
        "name": "Gareth Bale",
        "contract_price": 80000000,
        "age": 32,
        "efficiency": 2500000.00,
        "role": "Striker",
    },
    {
        "name": "Marc-André ter Stegen",
        "contract_price": 100000000,
        "age": 29,
        "efficiency": 3448275.86,
        "role": "Goalkeeper",
    },
    {
        "name": "Paul Pogba",
        "contract_price": 120000000,
        "age": 28,
        "efficiency": 4285714.29,
        "role": "Midfielder",
    },
    {
        "name": "Thibaut Courtois",
        "contract_price": 95000000,
        "age": 29,
        "efficiency": 3275862.07,
        "role": "Goalkeeper",
    },
    {
        "name": "Lautaro Martínez",
        "contract_price": 100000000,
        "age": 24,
        "efficiency": 4166666.67,
        "role": "Striker",
    },
    {
        "name": "Marco Reus",
        "contract_price": 80000000,
        "age": 32,
        "efficiency": 2500000.00,
        "role": "Forward",
    },
    {
        "name": "Serge Gnabry",
        "contract_price": 90000000,
        "age": 26,
        "efficiency": 3461538.46,
        "role": "Forward",
    },
    {
        "name": "Gianluigi Donnarumma",
        "contract_price": 80000000,
        "age": 22,
        "efficiency": 3658536.59,
        "role": "Goalkeeper",
    },
    {
        "name": "Phil Foden",
        "contract_price": 90000000,
        "age": 21,
        "efficiency": 4285714.29,
        "role": "Midfielder",
    }
]

football_clubs = [
    {"name": "Real Madrid", "city": "Madrid", "country": "Spain"},
    {"name": "FC Barcelona", "city": "Barcelona", "country": "Spain"},
    {"name": "Manchester United", "city": "Manchester", "country": "England"},
    {"name": "Liverpool FC", "city": "Liverpool", "country": "England"},
    {"name": "Bayern Munich", "city": "Munich", "country": "Germany"},
    {"name": "Borussia Dortmund", "city": "Dortmund", "country": "Germany"},
    {"name": "Paris Saint-Germain", "city": "Paris", "country": "France"},
    {"name": "Juventus", "city": "Turin", "country": "Italy"},
    {"name": "AC Milan", "city": "Milan", "country": "Italy"},
    {"name": "Inter Milan", "city": "Milan", "country": "Italy"},
    {"name": "Chelsea FC", "city": "London", "country": "England"},
    {"name": "Manchester City", "city": "Manchester", "country": "England"},
    {"name": "Arsenal FC", "city": "London", "country": "England"},
    {"name": "Tottenham Hotspur", "city": "London", "country": "England"},
    {"name": "Atletico Madrid", "city": "Madrid", "country": "Spain"},
    {"name": "Sevilla FC", "city": "Seville", "country": "Spain"},
    {"name": "AS Roma", "city": "Rome", "country": "Italy"},
    {"name": "Napoli", "city": "Naples", "country": "Italy"},
    {"name": "Ajax", "city": "Amsterdam", "country": "Netherlands"},
    {"name": "PSV Eindhoven", "city": "Eindhoven", "country": "Netherlands"},
    {"name": "FC Porto", "city": "Porto", "country": "Portugal"},
    {"name": "Benfica", "city": "Lisbon", "country": "Portugal"},
    {"name": "Sporting CP", "city": "Lisbon", "country": "Portugal"},
    {"name": "Borussia Mönchengladbach", "city": "Mönchengladbach", "country": "Germany"},
    {"name": "Lyon", "city": "Lyon", "country": "France"},
    {"name": "Marseille", "city": "Marseille", "country": "France"},
    {"name": "Valencia CF", "city": "Valencia", "country": "Spain"},
    {"name": "Villarreal CF", "city": "Villarreal", "country": "Spain"},
    {"name": "RB Leipzig", "city": "Leipzig", "country": "Germany"},
    {"name": "ACF Fiorentina", "city": "Florence", "country": "Italy"},
    {"name": "Leeds United", "city": "Leeds", "country": "England"},
]
