football_clubs = [
    {"name": "Real Madrid", "city": "Madrid", "country": "Spain", "stadium": "Santiago Bernabéu", "budget": 1000000000},
    {"name": "FC Barcelona", "city": "Barcelona", "country": "Spain", "stadium": "Camp Nou", "budget": 1000000000},
    {"name": "Manchester United", "city": "Manchester", "country": "England", "stadium": "Old Trafford",
     "budget": 1000000000},
    {"name": "Liverpool FC", "city": "Liverpool", "country": "England", "stadium": "Anfield", "budget": 1000000000},
    {"name": "Bayern Munich", "city": "Munich", "country": "Germany", "stadium": "Allianz Arena", "budget": 1000000000},
    {"name": "Borussia Dortmund", "city": "Dortmund", "country": "Germany", "stadium": "Signal Iduna Park",
     "budget": 1000000000},
    {"name": "Paris Saint-Germain", "city": "Paris", "country": "France", "stadium": "Parc des Princes",
     "budget": 1000000000},
    {"name": "Juventus", "city": "Turin", "country": "Italy", "stadium": "Allianz Stadium", "budget": 1000000000},
    {"name": "AC Milan", "city": "Milan", "country": "Italy", "stadium": "San Siro", "budget": 1000000000},
    {"name": "Inter Milan", "city": "Milan", "country": "Italy", "stadium": "San Siro", "budget": 1000000000},
    {"name": "Chelsea FC", "city": "London", "country": "England", "stadium": "Stamford Bridge", "budget": 1000000000},
    {"name": "Manchester City", "city": "Manchester", "country": "England", "stadium": "Etihad Stadium",
     "budget": 1000000000},
    {"name": "Arsenal FC", "city": "London", "country": "England", "stadium": "Emirates Stadium", "budget": 1000000000},
    {"name": "Tottenham Hotspur", "city": "London", "country": "England", "stadium": "Tottenham Hotspur Stadium",
     "budget": 1000000000},
    {"name": "Atletico Madrid", "city": "Madrid", "country": "Spain", "stadium": "Wanda Metropolitano",
     "budget": 1000000000},
    {"name": "Sevilla FC", "city": "Seville", "country": "Spain", "stadium": "Ramón Sánchez Pizjuán",
     "budget": 1000000000},
    {"name": "AS Roma", "city": "Rome", "country": "Italy", "stadium": "Stadio Olimpico", "budget": 1000000000},
    {"name": "Napoli", "city": "Naples", "country": "Italy", "stadium": "Stadio Diego Armando Maradona",
     "budget": 1000000000},
    {"name": "Ajax", "city": "Amsterdam", "country": "Netherlands", "stadium": "Johan Cruyff Arena",
     "budget": 1000000000},
    {"name": "PSV Eindhoven", "city": "Eindhoven", "country": "Netherlands", "stadium": "Philips Stadion",
     "budget": 1000000000},
    {"name": "FC Porto", "city": "Porto", "country": "Portugal", "stadium": "Estádio do Dragão", "budget": 1000000000},
    {"name": "Benfica", "city": "Lisbon", "country": "Portugal", "stadium": "Estádio da Luz", "budget": 1000000000},
    {"name": "Sporting CP", "city": "Lisbon", "country": "Portugal", "stadium": "Estádio José Alvalade",
     "budget": 1000000000},
    {"name": "Borussia Mönchengladbach", "city": "Mönchengladbach", "country": "Germany", "stadium": "Borussia-Park",
     "budget": 1000000000},
    {"name": "Lyon", "city": "Lyon", "country": "France", "stadium": "Groupama Stadium", "budget": 1000000000},
    {"name": "Marseille", "city": "Marseille", "country": "France", "stadium": "Orange Vélodrome",
     "budget": 1000000000},
    {"name": "Valencia CF", "city": "Valencia", "country": "Spain", "stadium": "Mestalla Stadium",
     "budget": 1000000000},
    {"name": "Villarreal CF", "city": "Villarreal", "country": "Spain", "stadium": "Estadio de la Cerámica",
     "budget": 1000000000},
    {"name": "RB Leipzig", "city": "Leipzig", "country": "Germany", "stadium": "Red Bull Arena", "budget": 1000000000},
    {"name": "ACF Fiorentina", "city": "Florence", "country": "Italy", "stadium": "Stadio Artemio Franchi",
     "budget": 1000000000},
    {"name": "Leeds United", "city": "Leeds", "country": "England", "stadium": "Elland Road", "budget": 1000000000},
]
