football_events = {
    "Shot on Goal": {"score": 0, "effectiveness": 0.7, "time": 0},
    "Corner Kick": {"score": 0, "effectiveness": 0.7, "time": 0},
    "Free Kick": {"score": 0, "effectiveness": 0.8, "time": 0},
    "Penalty Success": {"score": 1, "effectiveness": 0.9, "time": 0},
    "Penalty Kick": {"score": 0, "effectiveness": -0.1, "time": 0},
    "Yellow Card": {"score": 0, "effectiveness": -0.2, "time": 0},
    "Red Card": {"score": 0, "effectiveness": -0.5, "time": 0},
    "Offside": {"score": 0, "effectiveness": -0.1, "time": 0},
    "Substitution": {"score": 0, "effectiveness": 0.4, "time": 0},
    "Foul": {"score": 0, "effectiveness": -0.3, "time": 0},
    "Injury": {"score": 0, "effectiveness": -0.4, "time": 0},
    "Header": {"score": 0, "effectiveness": 0.6, "time": 0},
    "Save by the Goalkeeper": {"score": 0, "effectiveness": 0.7, "time": 0},
    "Additional Time": {"score": 0, "effectiveness": 0, "time": 3},
    "Rain Delay": {"score": 0, "effectiveness": 0, "time": 5},
    "Controversial Decision": {"score": 0, "effectiveness": -0.1, "time": 0},
    "Tackle": {"score": 0, "effectiveness": 0.1, "time": 0},
    "Own Goal": {"score": -1, "effectiveness": -1.0, "time": 0},
    "Crossbar Hit": {"score": 0, "effectiveness": 0.1, "time": 0},
    "Post Hit": {"score": 0, "effectiveness": 0.1, "time": 0},
    "Penalty Missed": {"score": 0, "effectiveness": 0.1, "time": 0},
    "Handball": {"score": 0, "effectiveness": -0.1, "time": 0},
    "Inspirational Pass": {"score": 0, "effectiveness": 0.1, "time": 0},
}
